//! Artisan Initialization State Machine
//!
//! Tracks the handshake sequence: CHAN → UNITS → FILT
//! States: Idle → ExpectingChan → ExpectingUnits → ExpectingFilt → Ready

use crate::config::ArtisanCommand;
use crate::input::parser::ParseError;

/// Initialization states for Artisan handshake
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InitState {
    Idle,           // No handshake started
    ExpectingChan,  // Waiting for CHAN command
    ExpectingUnits, // Waiting for UNITS command
    ExpectingFilt,  // Waiting for FILT command
    Ready,          // Handshake complete, ready for operational commands
}

/// Events generated by the initialization state machine
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InitEvent {
    ChanReceived,
    UnitsReceived,
    FiltReceived,
    OperationalCommand,
}

/// Tracks the full initialization handshake state
#[derive(Debug, Clone, Copy)]
pub struct ArtisanInitState {
    state: InitState,
    chan_value: Option<u16>,
    units_value: Option<bool>,
    filt_value: Option<u8>,
}

impl ArtisanInitState {
    /// Create a new initialization state machine
    /// Starts in ExpectingChan state (first step of handshake)
    pub fn new() -> Self {
        Self {
            state: InitState::ExpectingChan,
            chan_value: None,
            units_value: None,
            filt_value: None,
        }
    }

    /// Get the current state
    pub fn state(&self) -> InitState {
        self.state
    }

    /// Check if initialization is complete
    pub fn is_ready(&self) -> bool {
        self.state == InitState::Ready
    }

    /// Get the configured channel value
    pub fn chan_value(&self) -> Option<u16> {
        self.chan_value
    }

    /// Get the configured units value (true = Fahrenheit, false = Celsius)
    pub fn units_value(&self) -> Option<bool> {
        self.units_value
    }

    /// Get the configured filter value
    pub fn filt_value(&self) -> Option<u8> {
        self.filt_value
    }

    /// Process a command in the initialization sequence
    /// Returns the event that occurred or an error for invalid commands
    pub fn on_command(&mut self, command: ArtisanCommand) -> Result<InitEvent, ParseError> {
        match (self.state, command) {
            // CHAN command received - move to ExpectingUnits
            (InitState::ExpectingChan, ArtisanCommand::Chan(chan)) => {
                self.chan_value = Some(chan);
                self.state = InitState::ExpectingUnits;
                Ok(InitEvent::ChanReceived)
            }

            // UNITS command received - move to ExpectingFilt
            (InitState::ExpectingUnits, ArtisanCommand::Units(units)) => {
                self.units_value = Some(units);
                self.state = InitState::ExpectingFilt;
                Ok(InitEvent::UnitsReceived)
            }

            // FILT command received - initialization complete
            (InitState::ExpectingFilt, ArtisanCommand::Filt(filt)) => {
                self.filt_value = Some(filt);
                self.state = InitState::Ready;
                Ok(InitEvent::FiltReceived)
            }

            // Operational commands only valid in Ready state
            (_, ArtisanCommand::ReadStatus)
            | (_, ArtisanCommand::StartRoast)
            | (_, ArtisanCommand::SetHeater(_))
            | (_, ArtisanCommand::SetFan(_))
            | (_, ArtisanCommand::IncreaseHeater)
            | (_, ArtisanCommand::DecreaseHeater)
            | (_, ArtisanCommand::EmergencyStop) => {
                if self.state == InitState::Ready {
                    Ok(InitEvent::OperationalCommand)
                } else {
                    // Operational command received before initialization complete
                    Err(ParseError::UnknownCommand)
                }
            }

            // Wrong command for current state
            _ => Err(ParseError::UnknownCommand),
        }
    }

    /// Reset the state machine to initial state
    pub fn reset(&mut self) {
        self.state = InitState::ExpectingChan;
        self.chan_value = None;
        self.units_value = None;
        self.filt_value = None;
    }
}

impl Default for ArtisanInitState {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper to create a new state machine for testing
    fn new_state() -> ArtisanInitState {
        ArtisanInitState::new()
    }

    #[test]
    fn test_new_starts_expecting_chan() {
        let state = new_state();
        assert_eq!(state.state(), InitState::ExpectingChan);
        assert!(!state.is_ready());
    }

    #[test]
    fn test_chan_transition_to_expecting_units() {
        let mut state = new_state();

        let event = state.on_command(ArtisanCommand::Chan(1200));

        assert!(event.is_ok());
        assert_eq!(event.unwrap(), InitEvent::ChanReceived);
        assert_eq!(state.state(), InitState::ExpectingUnits);
        assert_eq!(state.chan_value(), Some(1200));
    }

    #[test]
    fn test_units_transition_to_expecting_filt() {
        let mut state = new_state();
        state.on_command(ArtisanCommand::Chan(1200)).unwrap();

        let event = state.on_command(ArtisanCommand::Units(false));

        assert!(event.is_ok());
        assert_eq!(event.unwrap(), InitEvent::UnitsReceived);
        assert_eq!(state.state(), InitState::ExpectingFilt);
        assert_eq!(state.units_value(), Some(false));
    }

    #[test]
    fn test_filt_transition_to_ready() {
        let mut state = new_state();
        state.on_command(ArtisanCommand::Chan(1200)).unwrap();
        state.on_command(ArtisanCommand::Units(false)).unwrap();

        let event = state.on_command(ArtisanCommand::Filt(5));

        assert!(event.is_ok());
        assert_eq!(event.unwrap(), InitEvent::FiltReceived);
        assert!(state.is_ready());
        assert_eq!(state.filt_value(), Some(5));
    }

    #[test]
    fn test_full_handshake_sequence() {
        let mut state = new_state();

        assert_eq!(state.state(), InitState::ExpectingChan);
        assert!(!state.is_ready());

        state.on_command(ArtisanCommand::Chan(1200)).unwrap();
        assert_eq!(state.state(), InitState::ExpectingUnits);

        state.on_command(ArtisanCommand::Units(true)).unwrap();
        assert_eq!(state.state(), InitState::ExpectingFilt);

        state.on_command(ArtisanCommand::Filt(3)).unwrap();
        assert!(state.is_ready());
        assert_eq!(state.chan_value(), Some(1200));
        assert_eq!(state.units_value(), Some(true));
        assert_eq!(state.filt_value(), Some(3));
    }

    #[test]
    fn test_wrong_command_returns_error() {
        let mut state = new_state();

        // Sending UNITS before CHAN should fail
        let result = state.on_command(ArtisanCommand::Units(false));
        assert!(matches!(result, Err(ParseError::UnknownCommand)));
    }

    #[test]
    fn test_operational_command_before_ready_returns_error() {
        let mut state = new_state();
        state.on_command(ArtisanCommand::Chan(1200)).unwrap();

        // READ command before initialization complete should fail
        let result = state.on_command(ArtisanCommand::ReadStatus);
        assert!(matches!(result, Err(ParseError::UnknownCommand)));
    }

    #[test]
    fn test_operational_command_allowed_when_ready() {
        let mut state = new_state();
        state.on_command(ArtisanCommand::Chan(1200)).unwrap();
        state.on_command(ArtisanCommand::Units(false)).unwrap();
        state.on_command(ArtisanCommand::Filt(5)).unwrap();

        // Now READ should be allowed
        let event = state.on_command(ArtisanCommand::ReadStatus);
        assert!(event.is_ok());
        assert_eq!(event.unwrap(), InitEvent::OperationalCommand);
    }

    #[test]
    fn test_reset_clears_all_state() {
        let mut state = new_state();
        state.on_command(ArtisanCommand::Chan(1200)).unwrap();
        state.on_command(ArtisanCommand::Units(false)).unwrap();
        state.on_command(ArtisanCommand::Filt(5)).unwrap();

        assert!(state.is_ready());

        state.reset();

        assert_eq!(state.state(), InitState::ExpectingChan);
        assert!(!state.is_ready());
        assert_eq!(state.chan_value(), None);
        assert_eq!(state.units_value(), None);
        assert_eq!(state.filt_value(), None);
    }

    #[test]
    fn test_all_operational_commands_allowed_when_ready() {
        let mut state = new_state();
        state.on_command(ArtisanCommand::Chan(1200)).unwrap();
        state.on_command(ArtisanCommand::Units(false)).unwrap();
        state.on_command(ArtisanCommand::Filt(5)).unwrap();

        assert!(state.on_command(ArtisanCommand::StartRoast).is_ok());
        assert!(state.on_command(ArtisanCommand::SetHeater(50)).is_ok());
        assert!(state.on_command(ArtisanCommand::SetFan(75)).is_ok());
        assert!(state.on_command(ArtisanCommand::EmergencyStop).is_ok());
    }
}
